### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by AdityaIndoori** [zpettry/boxer#7]
Hey, I got the following error after installing everything from

> pip3 install -r requirements.txt

successfully.

**COMMAND:** python3 boxer.py -u https://some.url.com/ -w all.txt -d some_db
**OUTPUT:**
    ______
    | ___ \
    | |_/ / _____  _____ _ __
    | ___ \/ _ \ \/ / _ \ '__|
    | |_/ / (_) >  <  __/ |
    \____/ \___/_/\_\___|_|

     Directory Bruteforcer

                 Zack Pettry

Traceback (most recent call last):
  File "boxer.py", line 200, in <module>
    main(**vars(args))
  File "boxer.py", line 82, in main
    word_list = l.read().splitlines()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 34: character maps to < undefined >

**Comment by AdityaIndoori** [comment]
adding UTF8 i.e, `open(WHATEVER_FILE_NAME_VARIABLE, encoding="utf8")`

 did the trick, however, the tool isn't brute-forcing anything. 

**NEW OUTPUT:**
 ______
    | ___ \
    | |_/ / _____  _____ _ __
    | ___ \/ _ \ \/ / _ \ '__|
    | |_/ / (_) >  <  __/ |
    \____/ \___/_/\_\___|_|

     Directory Bruteforcer

                 Zack Pettry


Starting bruteforce on https://signal.lob.com/ for response code(s) [200, 204, 301, 302, 307, 403]...


Time: 0.977837324142456 seconds.
Creating local database: some_db.json
Done.
